### ISSUE TITLE
Provide the ability to only return the latest price for an item

### ISSUE THREAD

**Issue by marvey11** [marvey11/amazing-web-api#17]
## Tasks
- [x] add a boolean query parameter `latest-price-only` to the GET methods of the `/wishlists` an `/wishlist-items` routes:
  * will imply `with-prices=true` if `with-prices` is not specified
  * will have no effect if `with-prices=false` is specified
  * for the `/wishlists` route will also have no effect if `with-items=false` is specified
- [x] update the service call
- [x] adapt the response accordingly

**Comment by marvey11** [comment]
The following SQL command seems to be doing the job'
```sql
SELECT item_id, item_title, latest_date, price.itemPrice AS latest_price, list_id
FROM prices AS price 
LEFT JOIN (
	SELECT item.id AS item_id, item.title AS item_title, MAX(price.itemDate) AS latest_date, item.wishlistId AS list_id
	FROM items AS item 
	LEFT JOIN prices AS price ON price.itemId = item.id 
	WHERE item.id = "abcdef" 
	GROUP BY item_id
) AS ldates ON ldates.item_id = price.itemId
WHERE price.itemDate = latest_date
```
Whereas the normal GET with all prices would be:
```sql
SELECT item.id AS item_id, item.title AS item_title, price.itemDate AS item_date, price.itemPrice AS item_price, item.wishlistId AS list_id
FROM items as item 
LEFT JOIN prices AS price ON item.id = price.itemId
WHERE item.id = "abcdef"
```

**Comment by marvey11** [comment]
Alternative SQL statement:
```sql
SELECT item.id AS item_id, item.title AS item_name, latest_date, price.itemPrice AS latest_price, item.wishlistId AS list_id
FROM items AS item
LEFT JOIN prices AS price ON item.id = price.itemId
LEFT JOIN (
	SELECT price.itemId AS item_id, MAX(price.itemDate) AS latest_date
	FROM prices AS price
	GROUP BY item_id
) AS ldates ON price.itemId = ldates.item_id
WHERE price.itemDate = latest_date```
